Install necessary dependencies

diff --git a/manager b/manager
--- a/manager
+++ b/manager
@@ -4,8 +4,13 @@
 #   ARCH build_native JDK deploy TRAVIS_PULL_REQUEST
 
 set -e
+
+to_arch() {
+  sed -e 's/^[Ii][3-6]86$/i386/;s/^[Xx]86$/i386/;s/^[Xx]\(86[-_]\)\{0,1\}64$/x86_64/;s/^[Aa][Mm][Dd]64$$/x86_64/'
+}
+
 OS="`uname -s`"
-HOST_ARCH="`uname -m`"
+HOST_ARCH="`uname -m | to_arch`"
 
 PKG_UPDATE=()
 PKG_ADD=()
@@ -16,94 +21,95 @@ build_x86_on_x64=false
 if [[ -z "$ARCH" ]]; then
   ARCH="${HOST_ARCH}"
 else
-  case "$ARCH" in
-    i386|i486|i586|i686|x86)
-      case "$HOST_ARCH" in
-        x86_64|amd64|x64)
-          build_x86_on_x64=true
-          ;;
-      esac
-      ;;
-  esac
+  ARCH=`printf '%s\n' "$ARCH" | to_arch`
+  if [[ "$ARCH" == i386 ]] && [[ "$HOST_ARCH" == x86_64 ]]; then
+    build_x86_on_x64=true
+  fi
 fi
 
-if [[ -n "$build_native" ]]; then
+native=false
+packages=()
+
+add_native() {
   native=true
   packages=(cmake libtool texinfo)
   maven_extra_config+=('-Pnative')
-else
-  native=false
-  packages=()
+}
+
+if [[ -n "$build_native" ]]; then
+  add_native
 fi
+
+guess_os_group() {
+  if command -v apt-get >/dev/null 2>&1; then os_group=debian
+  elif command -v yum >/dev/null 2>&1; then os_group=centos
+  else
+    echo 'Package manager not found' >&2
+    exit 1
+  fi
+}
+
+debian_pkg_manager() {
+  PKG_UPDATE=(sudo apt-get update -y)
+  PKG_QUERY_INSTALLED=(dkpg -l)
+  # -f fix-broken attempt to correct a system with broken dependencies in place
+  PKG_ADD=(sudo apt-get -f -y install)
+}
+
+debian_cxx_dep() {
+  packages+=(automake gcc g++)
+  if "$build_x86_on_x64"; then packages+=(g++-multilib); fi
+}
+
+centos_pkg_manager() {
+  # -y assume yes
+  PKG_ADD=(sudo yum install -y)
+  PKG_QUERY_INSTALLED=(yum list installed)
+}
+
+centos_cxx_dep() {
+  packages+=(automake gcc gcc-c++)
+  if "$build_x86_on_x64"; then
+    packages+=(glibc-devel.i686 libgcc.i686 libstdc++-devel.i686 ncurses-devel.i686)
+  fi
+}
+
+oraclejdk8() {
+  case "$ARCH" in
+    i386) JDK_ARCH=i586;;
+    x86_64) JDK_ARCH=x64;;
+    *) JDK_ARCH="$ARCH";;
+  esac
+  JDK_DOWNLOAD_URL="https://download.oracle.com/otn-pub/java/jdk/8u131-b11/d54c1d3a095b4ff2b6607d096fa80163/jdk-8u131-linux-${JDK_ARCH}.tar.gz"
+  export JAVA_HOME="`pwd`/jdk1.8.0_131"
+}
+
+debian_openjdk8() {
+  local JDK_ARCH="$ARCH"
+  if [[ "$ARCH" == x86_64 ]]; then JDK_ARCH="amd64"; fi
+  JDK_INSTALL_NAME="openjdk-8-jdk:${JDK_ARCH}"
+  export JAVA_HOME="/usr/lib/jvm/java-8-openjdk-${JDK_ARCH}"
+}
+
+centos_openjdk8() {
+  local JDK_ARCH="$ARCH"
+  if [[ "$ARCH" == i386 ]]; then JDK_ARCH="i686"; fi
+  JDK_INSTALL_NAME="java-1.8.0-openjdk-devel.${JDK_ARCH}"
+  export JAVA_HOME=`ls /usr/lib/jvm/java-1.8.0-openjdk-1.8*."${ARCH}" -rd1 | head -1`
+}
+
 case "${OS}" in
   CYGWIN*|MINGW*|MSYS*)
     PKG_ADD=(echo)
     ;;
   Linux)
-    if command -v apt-get >/dev/null 2>&1; then
-      PKG_UPDATE=(sudo apt-get update -y)
-      if "$native"; then
-        packages+=(automake gcc g++)
-        if "$build_x86_on_x64"; then packages+=(g++-multilib); fi
-      fi
-      # -f fix-broken attempt to correct a system with broken dependencies in place
-      PKG_ADD=(sudo apt-get -f -y install)
-    elif command -v yum >/dev/null 2>&1; then
-      if "$native"; then
-        packages+=(automake gcc gcc-c++)
-        if "$build_x86_on_x64"; then
-          packages+=(glibc-devel.i686 libgcc.i686 libstdc++-devel.i686 ncurses-devel.i686)
-        fi
-      fi
-      # -y assume yes
-      PKG_ADD=(sudo yum install -y)
-      PKG_QUERY_INSTALLED=(yum list installed)
-    else
-      echo 'Package manager not found' >&2
-      exit 1
-    fi
+    guess_os_group
+    "${os_group}_pkg_manager"
+    if "$native"; then "${os_group}_cxx_dep"; fi
     case "$JDK" in
-      oraclejdk8)
-        case "$ARCH" in
-          i386|i486|i586|i686|x86)
-            JDK_DOWNLOAD_URL=https://download.oracle.com/otn-pub/java/jdk/8u131-b11/d54c1d3a095b4ff2b6607d096fa80163/jdk-8u131-linux-i586.tar.gz
-            ;;
-          x86_64|amd64)
-            JDK_DOWNLOAD_URL=https://download.oracle.com/otn-pub/java/jdk/8u131-b11/d54c1d3a095b4ff2b6607d096fa80163/jdk-8u131-linux-x64.tar.gz
-            ;;
-          *)
-            echo "unknown arch ${ARCH}" >&2
-            exit 1
-            ;;
-        esac
-        export JAVA_HOME="`pwd`/jdk1.8.0_131"
-        ;;
-      openjdk8|openjdk9)
-        JDK_VERSION=`echo "$JDK" | sed -e 's/^openjdk//g'`
-        case "$ARCH" in
-          i386|i486|i586|i686|x86)
-            if command -v apt-get >/dev/null 2>&1; then
-                JDK_INSTALL_NAME="openjdk-${JDK_VERSION}-jdk:i386"
-                export JAVA_HOME="/usr/lib/jvm/java-${JDK_VERSION}-openjdk-i386"
-            else
-                JDK_INSTALL_NAME="java-1.${JDK_VERSION}.0-openjdk-devel.i686"
-                export JAVA_HOME=`ls /usr/lib/jvm/java-1.${JDK_VERSION}.0-openjdk-1.${JDK_VERSION}*.i386 -rd1 | head -1`
-            fi
-            ;;
-          x86_64|amd64|x64)
-            if command -v apt-get >/dev/null 2>&1; then
-              JDK_INSTALL_NAME="openjdk-${JDK_VERSION}-jdk:amd64"
-              export JAVA_HOME="/usr/lib/jvm/java-${JDK_VERSION}-openjdk-amd64"
-            else
-              JDK_INSTALL_NAME="java-1.${JDK_VERSION}.0-openjdk-devel.x86_64"
-              export JAVA_HOME=`ls /usr/lib/jvm/java-1.${JDK_VERSION}.0-openjdk-1.${JDK_VERSION}*.x86_64 -rd1 | head -1`
-            fi
-            ;;
-          *)
-            echo "unknown arch ${ARCH}" >&2
-            exit 1
-            ;;
-        esac
+      oraclejdk8) oraclejdk8;;
+      openjdk8)
+        "${os_group}_openjdk8"
         packages+=("$JDK_INSTALL_NAME")
         ;;
       *)
@@ -115,7 +121,7 @@ case "${OS}" in
   Darwin)
     PKG_ADD=(brew install)
     PKG_QUERY_INSTALLED=(brew list)
-    if "$native"; then packages+=(automake make); fi
+    if "$native"; then packages+=(automake coreutils gnu-sed make); fi
     echo 'cd /usr/local/lib && ln -s ../../lib/libSystem.B.dylib libgcc_s.10.4.dylib && ln -s ../../lib/libSystem.B.dylib libgcc_s.10.5.dylib' | bash || true
     ;;
   FreeBSD)
@@ -141,6 +147,12 @@ case "${OS}" in
     exit 1
     ;;
 esac
+
+install=(install)
+
+if [[ "$deploy" == true ]] &&  git config --get remote.origin.url 2>&1 | grep -F https://github.com/java-native-call/jnc-build -q && [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then
+  install=(deploy -s .travis/settings.xml)
+fi
 
 case "$1" in
   fetch)
@@ -174,10 +186,6 @@ case "$1" in
     ;;
   test|build|package)
     echo "JAVA_HOME: ${JAVA_HOME}"
-    if [[ "$deploy" == true ]] &&  git config --get remote.origin.url 2>&1 | grep -F https://github.com/java-native-call/jnc-build -q && [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then
-      chmod +x mvnw && ./mvnw "${maven_extra_config[@]}" deploy -s .travis/settings.xml "$@"
-    else
-      chmod +x mvnw && ./mvnw "${maven_extra_config[@]}" install "$@"
-    fi
+    chmod +x mvnw && ./mvnw "${maven_extra_config[@]}" "${install[@]}" "$@"
     ;;
 esac
