Support multiple actions

diff --git a/manager b/manager
--- a/manager
+++ b/manager
@@ -98,9 +98,22 @@ centos_openjdk8() {
   export JAVA_HOME=`ls /usr/lib/jvm/java-1.8.0-openjdk-1.8*."${ARCH}" -rd1 | head -1`
 }
 
+os_fix=
+
+darwin_fix() {
+  echo 'cd /usr/local/lib && ln -s ../../lib/libSystem.B.dylib libgcc_s.10.4.dylib && ln -s ../../lib/libSystem.B.dylib libgcc_s.10.5.dylib' | bash || true
+}
+
+linux_fix() {
+  echo 'cd /usr/lib/gcc/x86_64-*/4.8* && cp -n crtbeginT.o crtbeginT.orig.o && cp -f crtbeginS.o crtbeginT.o' | sudo bash || true
+}
+
+windows=false
+
 case "${OS}" in
   CYGWIN*|MINGW*|MSYS*)
     PKG_ADD=(echo)
+    windows=true
     ;;
   Linux)
     guess_os_group
@@ -116,13 +129,16 @@ case "${OS}" in
         # use default jdk
         ;;
     esac
-    echo 'cd /usr/lib/gcc/x86_64-*/4.8* && cp -n crtbeginT.o crtbeginT.orig.o && cp -f crtbeginS.o crtbeginT.o' | sudo bash || true
+    os_fix=linux_fix
     ;;
   Darwin)
+    pkg_query() {
+        brew list | grep -q "^$1$"
+    }
     PKG_ADD=(brew install)
-    PKG_QUERY_INSTALLED=(brew list)
+    PKG_QUERY_INSTALLED=(pkg_query)
     if "$native"; then packages+=(automake coreutils gnu-sed make); fi
-    echo 'cd /usr/local/lib && ln -s ../../lib/libSystem.B.dylib libgcc_s.10.4.dylib && ln -s ../../lib/libSystem.B.dylib libgcc_s.10.5.dylib' | bash || true
+    os_fix=darwin_fix
     ;;
   FreeBSD)
     PKG_ADD=(sudo pkg install -fy)
@@ -154,38 +170,107 @@ if [[ "$deploy" == true ]] &&  git config --get remote.origin.url 2>&1 | grep -F
   install=(deploy -s .travis/settings.xml)
 fi
 
-case "$1" in
-  fetch)
-    git fetch;;
-  reset)
-    git fetch
-    rm -rf *
-    git reset --hard origin/master
-    ;;
-  dependency)
-    if [[ -n "${JDK_DOWNLOAD_URL}" ]]; then
-      wget -O- --no-cookies -c --header "Cookie: oraclelicense=a" "${JDK_DOWNLOAD_URL}" | tar -zxf-
+fetch() {
+  git fetch
+}
+
+reset() {
+  git fetch
+  rm -rf *
+  git reset --hard origin/master
+}
+
+dependency() {
+  if [[ -n "${JDK_DOWNLOAD_URL}" ]]; then
+    wget -O- --no-cookies -c --header "Cookie: oraclelicense=a" "${JDK_DOWNLOAD_URL}" | tar -zxf-
+  fi
+  if [[ "${#packages[@]}" -gt 0 ]]; then
+    if [[ "${#PKG_QUERY_INSTALLED[@]}" -gt 0 ]]; then
+      local n_packages=()
+      local pkg
+      for pkg in "${packages[@]}"; do
+        if ! "${PKG_QUERY_INSTALLED[@]}" "$pkg" 2>/dev/null; then
+          n_packages+=("$pkg")
+        fi
+      done
+      packages=("${n_packages[@]}")
+      unset n_packages
     fi
     if [[ "${#packages[@]}" -gt 0 ]]; then
-      if [[ "${#PKG_QUERY_INSTALLED[@]}" -gt 0 ]]; then
-        n_packages=()
-        for pkg in "${packages[@]}"; do
-          if ! "${PKG_QUERY_INSTALLED[@]}" "$pkg" 2>/dev/null; then
-            n_packages+=("$pkg")
-          fi
-        done
-        packages=("${n_packages[@]}")
-        unset n_packages
-      fi
-      if [[ "${#packages[@]}" -gt 0 ]]; then
-        echo "Prepare install ${packages[@]}"
-        "${PKG_UPDATE[@]}"
-        "${PKG_ADD[@]}" "${packages[@]}" || true
-      fi
+      echo "Prepare install ${packages[@]}"
+      "${PKG_UPDATE[@]}"
+      "${PKG_ADD[@]}" "${packages[@]}" || true
     fi
-    ;;
-  test|build|package)
-    echo "JAVA_HOME: ${JAVA_HOME}"
-    chmod +x mvnw && ./mvnw "${maven_extra_config[@]}" "${install[@]}" "$@"
-    ;;
-esac
+  fi
+}
+
+maven_prepare() {
+  echo "JAVA_HOME: ${JAVA_HOME}"
+  if ! "$windows"; then chmod +x mvnw; fi
+}
+
+usage() {
+  echo "usage: env [ENV DEFINITION] `dirname "$0"`/`basename "$0"` actions [...extraMavenParam]"
+  echo ""
+  echo "Possible environment variables:"
+  indent="    "
+  echo "${indent}ARCH=x86_64|i386"
+  echo "${indent}build_native=1"
+  echo "${indent}JDK=oraclejdk8|openjdk8"
+  echo "${indent}deploy=true"
+  echo "${indent}TRAVIS_PULL_REQUEST=false"
+  echo ""
+  echo "Possible actions:"
+  echo "${indent}fix: fix compile error on current OS"
+  echo "${indent}fetch: execute git fetch"
+  echo "${indent}reset: fetch from git repository and hard reset"
+  echo "${indent}dependency: install dependencies"
+  echo "${indent}test: alias for \`./mvnw test\` with configuration defined in previous environment"
+  echo "${indent}package: alias for \`./mvnw package\` with configuration defined in previous environment"
+  echo "${indent}install: alias for \`./mvnw install\` with configuration defined in previous environment"
+}
+
+fix_os=false
+git_fetch=false
+git_reset=false
+install_dependency=false
+maven_test=false
+maven_package=false
+maven_install=false
+original_maven_params=()
+
+if [[ "$#" -gt 0 ]]; then
+  index=0
+  for i in "$@"; do
+    index=$((index+1))
+    case "$i" in
+      fix|os_fix|osfix|os-fix) fix_os=true;;
+      fetch) git_fetch=true;;
+      reset) git_reset=true;;
+      test) maven_test=true;;
+      dependency) install_dependency=true;;
+      package) maven_package=true;;
+      install) maven_install=true;;
+      *)
+        original_maven_params+=(${@:${index}})
+        break;;
+    esac
+  done
+
+  if "$fix_os" && [[ -n "$os_fix" ]]; then "$os_fix"; fi
+  if "$git_reset"; then reset; elif "$git_fetch"; then fetch; fi
+  if "$install_dependency"; then dependency; fi
+
+  maven_actions=()
+  if "$maven_install"; then maven_actions=(${install[@]})
+  elif "$maven_package"; then maven_actions=(package)
+  elif "$maven_test"; then maven_actions=(test); fi
+  maven_actions+=(${original_maven_params[@]})
+  if [[ "${#maven_actions[@]}" -gt 0 ]]; then
+    maven_prepare
+    echo ./mvnw "${maven_extra_config[@]}" "${maven_actions[@]}"
+    ./mvnw "${maven_extra_config[@]}" "${maven_actions[@]}"
+  fi
+else
+  usage
+fi
